/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PRAC.TQS;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
<<<<<<< HEAD
}
=======
}
/*
* dsada sd
*/
>>>>>>> 7192b1fcfceeda76ccc9148631435dd4ac4a7c3b
